#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

TARGET_PER_CLASS = 50
MAX_GITHUB_SIZE_KB = 10_000
LABELS = ("ai_generated", "ai_assisted", "human")

AI_QUERIES = {
    "ai_generated": (
        "built entirely with ChatGPT",
        "100% generated by ChatGPT",
        "fully generated by ChatGPT",
        "entirely written by ChatGPT",
        "entirely generated with Claude",
        "all the code was written by Claude",
        "completely generated by Claude",
        "created entirely by Claude Code",
        "all code is AI-generated",
        "100% AI-generated",
        "entirely vibe coded",
    ),
    "ai_assisted": (
        "with help from ChatGPT",
        "with assistance from ChatGPT",
        "created with help from ChatGPT",
        "developed with assistance from ChatGPT",
        "built with Cursor",
        "coded with Cursor",
        "made with GitHub Copilot",
        "built with GitHub Copilot",
        "developed with GitHub Copilot",
    ),
}

QUESTIONABLE_HUMAN_REPOS = {
    "PacktPublishing__Learn-LLVM-12",
    "bigscience-workshop__biomedical",
    "learning-zone__spring-boot-basics",
    "manifoldfinance__defi-threat",
    "rishabh-bansal__GitStart",
}


@dataclass(frozen=True)
class Candidate:
    label: str
    full_name: str
    clone_url: str
    html_url: str
    owner: str
    size_kb: int
    evidence_phrase: str

    @property
    def folder_name(self) -> str:
        owner, repo = self.full_name.split("/", maxsplit=1)
        return f"{owner}__{repo}"


def main() -> None:
    args = parse_args()
    project_root = Path(__file__).resolve().parents[1]
    corpus = (project_root / args.corpus).resolve()
    prep = corpus / "_prep"
    prep.mkdir(parents=True, exist_ok=True)

    if args.refresh_metadata:
        refresh_metadata(corpus, prep)
        return

    excluded = load_live_test_repos(prep)
    print(f"Live-test exclusions: {len(excluded)}", flush=True)

    with tempfile.TemporaryDirectory(prefix="gitzero-corpus-rebuild-") as temporary:
        staging = Path(temporary)
        selected: dict[str, list[Candidate]] = {}
        for label in ("ai_generated", "ai_assisted"):
            candidates = discover_candidates(label, excluded)
            print(f"{label}: {len(candidates)} evidence-backed candidates", flush=True)
            selected[label] = clone_verified_candidates(
                candidates,
                staging / label,
                target=args.target,
                jobs=args.jobs,
            )
            if len(selected[label]) < args.target:
                raise SystemExit(
                    f"Only {len(selected[label])} verified {label} repos; "
                    f"need {args.target}. Existing corpus was not changed."
                )

        backup = replace_real_repo_classes(corpus, staging, selected, target=args.target)
        rows = build_manifest(corpus, selected)
        write_jsonl(prep / "corpus_manifest_v7.jsonl", rows)
        write_lines(prep / "live_test_exclusions_v7.txt", sorted(excluded))
        inventory = build_inventory(corpus)
        write_jsonl(prep / "corpus_git_inventory_v7.jsonl", inventory)

    print("", flush=True)
    print("Corpus rebuild complete", flush=True)
    for label in (*LABELS, "template"):
        count = sum(1 for path in (corpus / label).iterdir() if path.is_dir())
        print(f"  {label}: {count}", flush=True)
    print(f"  backup: {backup}", flush=True)
    print(f"  manifest: {prep / 'corpus_manifest_v7.jsonl'}", flush=True)
    print(f"  inventory: {prep / 'corpus_git_inventory_v7.jsonl'}", flush=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rebuild GitZero's balanced, evidence-backed local corpus."
    )
    parser.add_argument("--corpus", type=Path, default=Path("corpus"))
    parser.add_argument("--target", type=int, default=TARGET_PER_CLASS)
    parser.add_argument("--jobs", type=int, default=4)
    parser.add_argument(
        "--refresh-metadata",
        action="store_true",
        help="Refresh the manifest and Git inventory without rebuilding repositories.",
    )
    return parser.parse_args()


def load_live_test_repos(prep: Path) -> set[str]:
    repos: set[str] = set()
    for path in sorted(prep.glob("live_test_exclusions*.txt")):
        for line in path.read_text(encoding="utf-8").splitlines():
            normalized = line.strip().lower()
            if normalized.count("/") == 1:
                repos.add(normalized)
    for path in sorted(prep.glob("github_*scan*.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            for key in ("source", "url", "repo_url"):
                value = row.get(key)
                normalized = normalize_repo_name(value) if isinstance(value, str) else None
                if normalized:
                    repos.add(normalized)
    return repos


def normalize_repo_name(value: str) -> str | None:
    prefix = "https://github.com/"
    if not value.startswith(prefix):
        return None
    name = value[len(prefix) :].strip("/")
    if name.endswith(".git"):
        name = name[:-4]
    return name.lower() if name.count("/") == 1 else None


def discover_candidates(label: str, excluded: set[str]) -> list[Candidate]:
    candidates: list[Candidate] = []
    seen_repos: set[str] = set()
    seen_owners: set[str] = set()
    for phrase in AI_QUERIES[label]:
        query = f'"{phrase}" in:readme fork:false archived:false'
        payload = github_search(query)
        for item in payload.get("items", []):
            candidate = candidate_from_item(label, phrase, item)
            if candidate is None:
                continue
            repo_key = candidate.full_name.lower()
            owner_key = candidate.owner.lower()
            if repo_key in excluded or repo_key in seen_repos or owner_key in seen_owners:
                continue
            if looks_like_catalog(candidate.full_name):
                continue
            seen_repos.add(repo_key)
            seen_owners.add(owner_key)
            candidates.append(candidate)
    return candidates


def github_search(query: str) -> dict[str, Any]:
    params = urllib.parse.urlencode({"q": query, "per_page": 100})
    url = f"https://api.github.com/search/repositories?{params}"
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "gitzero-corpus-builder",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"

    while True:
        request = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            if exc.code not in {403, 429}:
                raise
            reset = int(exc.headers.get("X-RateLimit-Reset", "0") or 0)
            wait_seconds = max(2, min(65, reset - int(time.time()) + 1))
            print(f"GitHub search rate limit; waiting {wait_seconds}s", flush=True)
            time.sleep(wait_seconds)


def candidate_from_item(label: str, phrase: str, item: dict[str, Any]) -> Candidate | None:
    full_name = str(item.get("full_name") or "")
    clone_url = str(item.get("clone_url") or "")
    html_url = str(item.get("html_url") or "")
    size_kb = int(item.get("size") or 0)
    owner = str((item.get("owner") or {}).get("login") or "")
    if not full_name or not clone_url or not html_url or not owner:
        return None
    if size_kb < 3 or size_kb > MAX_GITHUB_SIZE_KB:
        return None
    return Candidate(label, full_name, clone_url, html_url, owner, size_kb, phrase)


def looks_like_catalog(full_name: str) -> bool:
    lowered = full_name.lower()
    return any(
        token in lowered
        for token in (
            "awesome",
            "prompt-collection",
            "prompts",
            "repo-list",
            "repositories",
            "stars",
        )
    )


def clone_verified_candidates(
    candidates: list[Candidate],
    destination: Path,
    *,
    target: int,
    jobs: int,
) -> list[Candidate]:
    destination.mkdir(parents=True, exist_ok=True)
    selected: list[Candidate] = []
    for start in range(0, len(candidates), max(jobs * 3, 6)):
        if len(selected) >= target:
            break
        batch = candidates[start : start + max(jobs * 3, 6)]
        with ThreadPoolExecutor(max_workers=max(1, jobs)) as executor:
            futures = {
                executor.submit(clone_and_verify, candidate, destination): candidate
                for candidate in batch
            }
            for future in as_completed(futures):
                candidate = futures[future]
                ok, reason = future.result()
                if ok and len(selected) < target:
                    selected.append(candidate)
                    print(
                        f"accepted {candidate.label} [{len(selected)}/{target}]: "
                        f"{candidate.full_name}",
                        flush=True,
                    )
                else:
                    shutil.rmtree(destination / candidate.folder_name, ignore_errors=True)
                    if not ok:
                        print(f"rejected {candidate.full_name}: {reason}", flush=True)
    return selected


def clone_and_verify(candidate: Candidate, destination: Path) -> tuple[bool, str]:
    target = destination / candidate.folder_name
    result = subprocess.run(
        ["git", "clone", "--quiet", "--no-tags", candidate.clone_url, str(target)],
        text=True,
        capture_output=True,
        check=False,
        timeout=300,
    )
    if result.returncode != 0:
        return False, result.stderr.strip() or "clone failed"
    if is_shallow(target):
        return False, "clone is shallow"
    if git_output(target, "rev-list", "--count", "HEAD") in {"", "0"}:
        return False, "no commits"
    if not readme_contains(target, candidate.evidence_phrase):
        return False, f"evidence phrase not found: {candidate.evidence_phrase!r}"
    return True, "ok"


def readme_contains(repo: Path, phrase: str) -> bool:
    needle = phrase.casefold()
    for path in repo.rglob("README*"):
        if ".git" in path.parts or not path.is_file():
            continue
        try:
            if path.stat().st_size > 1_000_000:
                continue
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if needle in text.casefold():
            return True
    return False


def replace_real_repo_classes(
    corpus: Path,
    staging: Path,
    selected: dict[str, list[Candidate]],
    *,
    target: int,
) -> Path:
    current_human = corpus / "human"
    human_names = [
        path.name
        for path in sorted(current_human.iterdir(), key=lambda item: item.name.casefold())
        if path.is_dir() and path.name not in QUESTIONABLE_HUMAN_REPOS
    ]
    if len(human_names) < target:
        raise SystemExit(f"Only {len(human_names)} suitable human repos; need {target}.")

    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    backup = Path(tempfile.gettempdir()) / f"gitzero-corpus-backup-{timestamp}"
    backup.mkdir(parents=True, exist_ok=False)

    for label in LABELS:
        source = corpus / label
        if source.exists():
            shutil.move(str(source), str(backup / label))
        (corpus / label).mkdir(parents=True, exist_ok=True)

    for label in ("ai_generated", "ai_assisted"):
        for candidate in selected[label][:target]:
            shutil.move(
                str(staging / label / candidate.folder_name),
                str(corpus / label / candidate.folder_name),
            )

    old_human = backup / "human"
    for name in human_names[:target]:
        path = old_human / name
        shutil.move(str(path), str(corpus / "human" / path.name))
    return backup


def build_manifest(
    corpus: Path, selected: dict[str, list[Candidate]]
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for label in ("ai_generated", "ai_assisted"):
        for candidate in sorted(selected[label], key=lambda item: item.full_name.casefold()):
            rows.append(
                {
                    "label": label,
                    "repo": candidate.full_name,
                    "relative_path": f"{label}/{candidate.folder_name}",
                    "url": candidate.html_url,
                    "label_evidence": candidate.evidence_phrase,
                    "evidence_source": "GitHub README search",
                }
            )
    for path in sorted((corpus / "human").iterdir(), key=lambda item: item.name.casefold()):
        rows.append(
            {
                "label": "human",
                "repo": path.name.replace("__", "/", 1),
                "relative_path": f"human/{path.name}",
                "url": remote_url(path),
                "label_evidence": "Established pre-AI/open-source history; manually curated",
                "evidence_source": "existing verified corpus",
            }
        )
    rows.extend(template_manifest_rows(corpus))
    return rows


def template_manifest_rows(corpus: Path) -> list[dict[str, Any]]:
    return [
        {
            "label": "template",
            "repo": path.name,
            "relative_path": f"template/{path.name}",
            "url": "",
            "label_evidence": "Unmodified generated starter scaffold",
            "evidence_source": "official/local project generator",
        }
        for path in sorted(
            (corpus / "template").iterdir(), key=lambda item: item.name.casefold()
        )
        if path.is_dir()
    ]


def refresh_metadata(corpus: Path, prep: Path) -> None:
    manifest_path = prep / "corpus_manifest_v7.jsonl"
    existing = [
        json.loads(line)
        for line in manifest_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    rows = [row for row in existing if row.get("label") != "template"]
    rows.extend(template_manifest_rows(corpus))
    write_jsonl(manifest_path, rows)
    inventory_path = prep / "corpus_git_inventory_v7.jsonl"
    write_jsonl(inventory_path, build_inventory(corpus))
    print(f"metadata refreshed: {len(rows)} manifest rows", flush=True)
    print(f"manifest: {manifest_path}", flush=True)
    print(f"inventory: {inventory_path}", flush=True)


def build_inventory(corpus: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for label in (*LABELS, "template"):
        label_dir = corpus / label
        for path in sorted(label_dir.iterdir(), key=lambda item: item.name.casefold()):
            if not path.is_dir():
                continue
            rows.append(
                {
                    "label": label,
                    "repo": path.name,
                    "relative_path": f"{label}/{path.name}",
                    "is_git_repo": (path / ".git").exists(),
                    "is_shallow": is_shallow(path),
                    "commit_count": integer_git_output(path, "rev-list", "--count", "HEAD"),
                    "author_count": integer_git_output(
                        path, "shortlog", "-sne", "--all", transform="line_count"
                    ),
                    "remote_url": remote_url(path),
                }
            )
    return rows


def is_shallow(repo: Path) -> bool:
    return git_output(repo, "rev-parse", "--is-shallow-repository") == "true"


def remote_url(repo: Path) -> str:
    value = git_output(repo, "remote", "get-url", "origin")
    if value.endswith(".git"):
        value = value[:-4]
    return value


def git_output(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        text=True,
        capture_output=True,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def integer_git_output(
    repo: Path, *args: str, transform: str | None = None
) -> int:
    value = git_output(repo, *args)
    if transform == "line_count":
        return len([line for line in value.splitlines() if line.strip()])
    return int(value) if value.isdigit() else 0


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    text = "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows)
    path.write_text(text, encoding="utf-8")


def write_lines(path: Path, lines: list[str]) -> None:
    path.write_text("".join(f"{line}\n" for line in lines), encoding="utf-8")


if __name__ == "__main__":
    main()
